# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft.proto',
  package='raft',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nraft.proto\x12\x04raft\"\xa2\x01\n\x14\x41ppendEntriesRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_term\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x04 \x01(\x03\x12\x15\n\rlast_log_term\x18\x05 \x01(\x05\x12\x12\n\nop_entries\x18\x06 \x03(\t\x12\x1b\n\x13leader_commit_index\x18\x07 \x01(\x05\"O\n\x12\x41ppendEntriesReply\x12\x12\n\nreplier_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_term\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\"h\n\x0bVoteRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_term\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"z\n\tVoteReply\x12\x12\n\nreplier_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_term\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x05 \x01(\x08\"%\n\rSubmitRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\x05\"2\n\x0bSubmitReply\x12\x12\n\nreplier_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb4\x01\n\x04Raft\x12G\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply(\x01\x12\x31\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x0f.raft.VoteReply\x12\x30\n\x06Submit\x12\x13.raft.SubmitRequest\x1a\x11.raft.SubmitReplyb\x06proto3'
)




_APPENDENTRIESREQUEST = _descriptor.Descriptor(
  name='AppendEntriesRequest',
  full_name='raft.AppendEntriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requester_id', full_name='raft.AppendEntriesRequest.requester_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_term', full_name='raft.AppendEntriesRequest.current_term', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_log_index', full_name='raft.AppendEntriesRequest.last_log_index', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_log_term', full_name='raft.AppendEntriesRequest.last_log_term', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op_entries', full_name='raft.AppendEntriesRequest.op_entries', index=4,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leader_commit_index', full_name='raft.AppendEntriesRequest.leader_commit_index', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=183,
)


_APPENDENTRIESREPLY = _descriptor.Descriptor(
  name='AppendEntriesReply',
  full_name='raft.AppendEntriesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='replier_id', full_name='raft.AppendEntriesReply.replier_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_term', full_name='raft.AppendEntriesReply.current_term', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='raft.AppendEntriesReply.success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=264,
)


_VOTEREQUEST = _descriptor.Descriptor(
  name='VoteRequest',
  full_name='raft.VoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requester_id', full_name='raft.VoteRequest.requester_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_term', full_name='raft.VoteRequest.current_term', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_log_index', full_name='raft.VoteRequest.last_log_index', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_log_term', full_name='raft.VoteRequest.last_log_term', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=370,
)


_VOTEREPLY = _descriptor.Descriptor(
  name='VoteReply',
  full_name='raft.VoteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='replier_id', full_name='raft.VoteReply.replier_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_term', full_name='raft.VoteReply.current_term', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_log_index', full_name='raft.VoteReply.last_log_index', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_log_term', full_name='raft.VoteReply.last_log_term', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vote_granted', full_name='raft.VoteReply.vote_granted', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=494,
)


_SUBMITREQUEST = _descriptor.Descriptor(
  name='SubmitRequest',
  full_name='raft.SubmitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requester_id', full_name='raft.SubmitRequest.requester_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=533,
)


_SUBMITREPLY = _descriptor.Descriptor(
  name='SubmitReply',
  full_name='raft.SubmitReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='replier_id', full_name='raft.SubmitReply.replier_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='raft.SubmitReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=585,
)

DESCRIPTOR.message_types_by_name['AppendEntriesRequest'] = _APPENDENTRIESREQUEST
DESCRIPTOR.message_types_by_name['AppendEntriesReply'] = _APPENDENTRIESREPLY
DESCRIPTOR.message_types_by_name['VoteRequest'] = _VOTEREQUEST
DESCRIPTOR.message_types_by_name['VoteReply'] = _VOTEREPLY
DESCRIPTOR.message_types_by_name['SubmitRequest'] = _SUBMITREQUEST
DESCRIPTOR.message_types_by_name['SubmitReply'] = _SUBMITREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppendEntriesRequest = _reflection.GeneratedProtocolMessageType('AppendEntriesRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.AppendEntriesRequest)
  })
_sym_db.RegisterMessage(AppendEntriesRequest)

AppendEntriesReply = _reflection.GeneratedProtocolMessageType('AppendEntriesReply', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.AppendEntriesReply)
  })
_sym_db.RegisterMessage(AppendEntriesReply)

VoteRequest = _reflection.GeneratedProtocolMessageType('VoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOTEREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.VoteRequest)
  })
_sym_db.RegisterMessage(VoteRequest)

VoteReply = _reflection.GeneratedProtocolMessageType('VoteReply', (_message.Message,), {
  'DESCRIPTOR' : _VOTEREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.VoteReply)
  })
_sym_db.RegisterMessage(VoteReply)

SubmitRequest = _reflection.GeneratedProtocolMessageType('SubmitRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.SubmitRequest)
  })
_sym_db.RegisterMessage(SubmitRequest)

SubmitReply = _reflection.GeneratedProtocolMessageType('SubmitReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.SubmitReply)
  })
_sym_db.RegisterMessage(SubmitReply)



_RAFT = _descriptor.ServiceDescriptor(
  name='Raft',
  full_name='raft.Raft',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=588,
  serialized_end=768,
  methods=[
  _descriptor.MethodDescriptor(
    name='AppendEntries',
    full_name='raft.Raft.AppendEntries',
    index=0,
    containing_service=None,
    input_type=_APPENDENTRIESREQUEST,
    output_type=_APPENDENTRIESREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestVote',
    full_name='raft.Raft.RequestVote',
    index=1,
    containing_service=None,
    input_type=_VOTEREQUEST,
    output_type=_VOTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Submit',
    full_name='raft.Raft.Submit',
    index=2,
    containing_service=None,
    input_type=_SUBMITREQUEST,
    output_type=_SUBMITREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFT)

DESCRIPTOR.services_by_name['Raft'] = _RAFT

# @@protoc_insertion_point(module_scope)
