# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft.proto',
  package='raft',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nraft.proto\x12\x04raft\"\xa7\x01\n\x14\x41ppendEntriesMessage\x12\x10\n\x08leaderID\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x03\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\x12\"\n\nlogEntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x19\n\x11leaderCommitIndex\x18\x06 \x01(\x05\"Q\n\x15\x41ppendEntriesResponse\x12\x12\n\nfollowerID\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\">\n\x12RequestVoteMessage\x12\x13\n\x0b\x63\x61ndidateID\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\"?\n\x13RequestVoteResponse\x12\x13\n\x0b\x63urrentTerm\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\".\n\x10SetKeyValMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"$\n\x11SetKeyValResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rGetValMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"0\n\x0eGetValResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"<\n\x11GetLeaderResponse\x12\x10\n\x08leaderID\x18\x01 \x01(\x05\x12\x15\n\rleaderAddress\x18\x02 \x01(\t\"N\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12%\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\x14.raft.CommandMessage\"?\n\x0e\x43ommandMessage\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x0e\n\x0c\x45mptyMessage2\xc1\x02\n\x04Raft\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesMessage\x1a\x1b.raft.AppendEntriesResponse\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteMessage\x1a\x19.raft.RequestVoteResponse\x12\x38\n\tGetLeader\x12\x12.raft.EmptyMessage\x1a\x17.raft.GetLeaderResponse\x12<\n\tSetKeyVal\x12\x16.raft.SetKeyValMessage\x1a\x17.raft.SetKeyValResponse\x12\x33\n\x06GetVal\x12\x13.raft.GetValMessage\x1a\x14.raft.GetValResponseb\x06proto3'
)




_APPENDENTRIESMESSAGE = _descriptor.Descriptor(
  name='AppendEntriesMessage',
  full_name='raft.AppendEntriesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='leaderID', full_name='raft.AppendEntriesMessage.leaderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentTerm', full_name='raft.AppendEntriesMessage.currentTerm', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastLogIndex', full_name='raft.AppendEntriesMessage.lastLogIndex', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastLogTerm', full_name='raft.AppendEntriesMessage.lastLogTerm', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logEntries', full_name='raft.AppendEntriesMessage.logEntries', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaderCommitIndex', full_name='raft.AppendEntriesMessage.leaderCommitIndex', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=188,
)


_APPENDENTRIESRESPONSE = _descriptor.Descriptor(
  name='AppendEntriesResponse',
  full_name='raft.AppendEntriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='followerID', full_name='raft.AppendEntriesResponse.followerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentTerm', full_name='raft.AppendEntriesResponse.currentTerm', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='raft.AppendEntriesResponse.success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=271,
)


_REQUESTVOTEMESSAGE = _descriptor.Descriptor(
  name='RequestVoteMessage',
  full_name='raft.RequestVoteMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='candidateID', full_name='raft.RequestVoteMessage.candidateID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentTerm', full_name='raft.RequestVoteMessage.currentTerm', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=335,
)


_REQUESTVOTERESPONSE = _descriptor.Descriptor(
  name='RequestVoteResponse',
  full_name='raft.RequestVoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentTerm', full_name='raft.RequestVoteResponse.currentTerm', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voteGranted', full_name='raft.RequestVoteResponse.voteGranted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=400,
)


_SETKEYVALMESSAGE = _descriptor.Descriptor(
  name='SetKeyValMessage',
  full_name='raft.SetKeyValMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='raft.SetKeyValMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='raft.SetKeyValMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=448,
)


_SETKEYVALRESPONSE = _descriptor.Descriptor(
  name='SetKeyValResponse',
  full_name='raft.SetKeyValResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='raft.SetKeyValResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=486,
)


_GETVALMESSAGE = _descriptor.Descriptor(
  name='GetValMessage',
  full_name='raft.GetValMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='raft.GetValMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=516,
)


_GETVALRESPONSE = _descriptor.Descriptor(
  name='GetValResponse',
  full_name='raft.GetValResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='raft.GetValResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='raft.GetValResponse.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=566,
)


_GETLEADERRESPONSE = _descriptor.Descriptor(
  name='GetLeaderResponse',
  full_name='raft.GetLeaderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='leaderID', full_name='raft.GetLeaderResponse.leaderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaderAddress', full_name='raft.GetLeaderResponse.leaderAddress', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=568,
  serialized_end=628,
)


_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='raft.LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='raft.LogEntry.index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='term', full_name='raft.LogEntry.term', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='raft.LogEntry.command', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=708,
)


_COMMANDMESSAGE = _descriptor.Descriptor(
  name='CommandMessage',
  full_name='raft.CommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='raft.CommandMessage.operation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='raft.CommandMessage.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='raft.CommandMessage.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=710,
  serialized_end=773,
)


_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='raft.EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=789,
)

_APPENDENTRIESMESSAGE.fields_by_name['logEntries'].message_type = _LOGENTRY
_LOGENTRY.fields_by_name['command'].message_type = _COMMANDMESSAGE
DESCRIPTOR.message_types_by_name['AppendEntriesMessage'] = _APPENDENTRIESMESSAGE
DESCRIPTOR.message_types_by_name['AppendEntriesResponse'] = _APPENDENTRIESRESPONSE
DESCRIPTOR.message_types_by_name['RequestVoteMessage'] = _REQUESTVOTEMESSAGE
DESCRIPTOR.message_types_by_name['RequestVoteResponse'] = _REQUESTVOTERESPONSE
DESCRIPTOR.message_types_by_name['SetKeyValMessage'] = _SETKEYVALMESSAGE
DESCRIPTOR.message_types_by_name['SetKeyValResponse'] = _SETKEYVALRESPONSE
DESCRIPTOR.message_types_by_name['GetValMessage'] = _GETVALMESSAGE
DESCRIPTOR.message_types_by_name['GetValResponse'] = _GETVALRESPONSE
DESCRIPTOR.message_types_by_name['GetLeaderResponse'] = _GETLEADERRESPONSE
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.message_types_by_name['CommandMessage'] = _COMMANDMESSAGE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppendEntriesMessage = _reflection.GeneratedProtocolMessageType('AppendEntriesMessage', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.AppendEntriesMessage)
  })
_sym_db.RegisterMessage(AppendEntriesMessage)

AppendEntriesResponse = _reflection.GeneratedProtocolMessageType('AppendEntriesResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.AppendEntriesResponse)
  })
_sym_db.RegisterMessage(AppendEntriesResponse)

RequestVoteMessage = _reflection.GeneratedProtocolMessageType('RequestVoteMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.RequestVoteMessage)
  })
_sym_db.RegisterMessage(RequestVoteMessage)

RequestVoteResponse = _reflection.GeneratedProtocolMessageType('RequestVoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTERESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.RequestVoteResponse)
  })
_sym_db.RegisterMessage(RequestVoteResponse)

SetKeyValMessage = _reflection.GeneratedProtocolMessageType('SetKeyValMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETKEYVALMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.SetKeyValMessage)
  })
_sym_db.RegisterMessage(SetKeyValMessage)

SetKeyValResponse = _reflection.GeneratedProtocolMessageType('SetKeyValResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETKEYVALRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.SetKeyValResponse)
  })
_sym_db.RegisterMessage(SetKeyValResponse)

GetValMessage = _reflection.GeneratedProtocolMessageType('GetValMessage', (_message.Message,), {
  'DESCRIPTOR' : _GETVALMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.GetValMessage)
  })
_sym_db.RegisterMessage(GetValMessage)

GetValResponse = _reflection.GeneratedProtocolMessageType('GetValResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETVALRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.GetValResponse)
  })
_sym_db.RegisterMessage(GetValResponse)

GetLeaderResponse = _reflection.GeneratedProtocolMessageType('GetLeaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLEADERRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.GetLeaderResponse)
  })
_sym_db.RegisterMessage(GetLeaderResponse)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)

CommandMessage = _reflection.GeneratedProtocolMessageType('CommandMessage', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.CommandMessage)
  })
_sym_db.RegisterMessage(CommandMessage)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:raft.EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)



_RAFT = _descriptor.ServiceDescriptor(
  name='Raft',
  full_name='raft.Raft',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=792,
  serialized_end=1113,
  methods=[
  _descriptor.MethodDescriptor(
    name='AppendEntries',
    full_name='raft.Raft.AppendEntries',
    index=0,
    containing_service=None,
    input_type=_APPENDENTRIESMESSAGE,
    output_type=_APPENDENTRIESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestVote',
    full_name='raft.Raft.RequestVote',
    index=1,
    containing_service=None,
    input_type=_REQUESTVOTEMESSAGE,
    output_type=_REQUESTVOTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLeader',
    full_name='raft.Raft.GetLeader',
    index=2,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_GETLEADERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetKeyVal',
    full_name='raft.Raft.SetKeyVal',
    index=3,
    containing_service=None,
    input_type=_SETKEYVALMESSAGE,
    output_type=_SETKEYVALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetVal',
    full_name='raft.Raft.GetVal',
    index=4,
    containing_service=None,
    input_type=_GETVALMESSAGE,
    output_type=_GETVALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFT)

DESCRIPTOR.services_by_name['Raft'] = _RAFT

# @@protoc_insertion_point(module_scope)
